package sn.esmt.gymManagement.models.beans.enums;

public enum TypePrivilege {
	CREATE_DIRECTOR,
	UPDATE_DIRECTOR,
	READ_DIRECTOR,
	DELETE_DIRECTOR,
	
	CREATE_MANAGER,
	UPDATE_MANAGER,
	READ_MANAGER,
	DELETE_MANAGER,
	
	CREATE_RECEPTIONIST,
	UPDATE_RECEPTIONIST,
	READ_RECEPTIONIST,
	DELETE_RECEPTIONIST,
	
	CREATE_CLIENT,
	UPDATE_CLIENT,
	READ_CLIENT,
	DELETE_CLIENT,
	
	SAVE_PAIEMENT,
	
	VIEW_CLIENT_PROFILE,
	VIEW_FINANCIAL_STATISTIC,
	VIEW_NUMBER_CLIENT,
	VIEW_STATISTIC
}
